# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4935eb59d8f0a0a0c547645594c4991b84f13f257f5c8028490b493edd6fa02253e432c5a31ba9cc6e662cd440245e1068a0f337bfb719a589891009bb3b4e6

test:
  secret_key_base: f438cac22fffccebe45991c62336068b94883ff74d8e46be83d78b1a1eb5e8f8492e24c9ad90b7ddf0ff5bb0ee1d7eabf9cbdab1199000d3d73a6f78edd1e5bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
